{{- define "service.app" -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: "ahoy"
    app.kubernetes.io/version: {{ .glob.releaseVersion | quote }}
    app.kubernetes.io/release-name: {{ .glob.releaseName | quote }}
    app.kubernetes.io/name: {{ .app.name | quote }}
    app.kubernetes.io/build: {{ .app.version | quote }}
  name: {{ .app.name }}
spec:
  ports:
    {{- range $containerName, $container := .app.containers }}
    {{- range $container.servicePorts }}
    - name: {{ . }}-tcp
      port: {{ . }}
      protocol: TCP
      targetPort: {{ . }}
    {{- end }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ .app.name | quote }}
    app.kubernetes.io/instance: {{ .glob.releaseName | quote }}
  sessionAffinity: None
  {{- if and .app.routeEnabled .app.routeHostname .app.routeTargetPort }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
{{- end -}}
